### ISSUE TITLE
How to cache specific file?

### ISSUE THREAD

**Issue by elfeffe** [guerrerocarlos/CacheP2P#13]
How to cache specific file instead of page?
For example a big gif image or a swf video.

**Comment by deckar01** [comment]
As far as I can tell, only the HTML gets cached. Static assets are still being requested from the remote server. You should theoretically be able to seed any asset on the page, but this library would need additional logic to handle inserting it into the page. It might be easier to inline assets as data URLs so that they are captured as part of the existing HTML payload.

**Comment by elfeffe** [comment]
Ok, will check. Thank you
